// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozonva/ova-account-api/internal/metrics (interfaces: AccountMetrics)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAccountMetrics is a mock of AccountMetrics interface.
type MockAccountMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockAccountMetricsMockRecorder
}

// MockAccountMetricsMockRecorder is the mock recorder for MockAccountMetrics.
type MockAccountMetricsMockRecorder struct {
	mock *MockAccountMetrics
}

// NewMockAccountMetrics creates a new mock instance.
func NewMockAccountMetrics(ctrl *gomock.Controller) *MockAccountMetrics {
	mock := &MockAccountMetrics{ctrl: ctrl}
	mock.recorder = &MockAccountMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountMetrics) EXPECT() *MockAccountMetricsMockRecorder {
	return m.recorder
}

// IncCreatedCounter mocks base method.
func (m *MockAccountMetrics) IncCreatedCounter() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncCreatedCounter")
}

// IncCreatedCounter indicates an expected call of IncCreatedCounter.
func (mr *MockAccountMetricsMockRecorder) IncCreatedCounter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncCreatedCounter", reflect.TypeOf((*MockAccountMetrics)(nil).IncCreatedCounter))
}

// IncRemovedCounter mocks base method.
func (m *MockAccountMetrics) IncRemovedCounter() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncRemovedCounter")
}

// IncRemovedCounter indicates an expected call of IncRemovedCounter.
func (mr *MockAccountMetricsMockRecorder) IncRemovedCounter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncRemovedCounter", reflect.TypeOf((*MockAccountMetrics)(nil).IncRemovedCounter))
}

// IncUpdatedCounter mocks base method.
func (m *MockAccountMetrics) IncUpdatedCounter() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncUpdatedCounter")
}

// IncUpdatedCounter indicates an expected call of IncUpdatedCounter.
func (mr *MockAccountMetricsMockRecorder) IncUpdatedCounter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncUpdatedCounter", reflect.TypeOf((*MockAccountMetrics)(nil).IncUpdatedCounter))
}

// IncreaseCreatedCounter mocks base method.
func (m *MockAccountMetrics) IncreaseCreatedCounter(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncreaseCreatedCounter", arg0)
}

// IncreaseCreatedCounter indicates an expected call of IncreaseCreatedCounter.
func (mr *MockAccountMetricsMockRecorder) IncreaseCreatedCounter(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseCreatedCounter", reflect.TypeOf((*MockAccountMetrics)(nil).IncreaseCreatedCounter), arg0)
}
