version: "3.8"

services:

  db:
    image: postgres:13
#    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${DB_PORT}:5432

  jaeger:
    image: jaegertracing/all-in-one:1.21
#    restart: always
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686" # Jaeger UI

volumes:
  database:
    driver: local
