version: "3.8"

services:

  db:
    image: postgres:13
#    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${DB_PORT}:5432

  jaeger:
    image: jaegertracing/all-in-one:1.21
#    restart: always
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686" # Jaeger UI

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
    - '2181:2181'
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
    - '9092:9092'
    environment:
    - KAFKA_BROKER_ID=1
    - KAFKA_LISTENERS=PLAINTEXT://:9092
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
    - zookeeper

volumes:
  database:
    driver: local
